---
- hosts: local
  become: yes
  tasks:
  - name: "file changes"
    lineinfile:
      path: '{{ filepath }}'
      regexp: '^SELINUX='
      line: 'SELINUX=enforcing'
  # Add a line to a file if it does not exist, without passing regexp
  - lineinfile:
      path: '{{ filepath }}'
      line: '192.168.1.99 foo.lab.net foo'     
  
#  vars:
#    filepath: /home/ansible/testlineinfile

